version: "3.9"
services:
  app:
    container_name: recipe_container
    build: 
      context: .
      args: 
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db


  db: 
    image: postgres:13-alpine
    volumes: 
      - dev-db-data:/var/lib/postg0ersql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}



volumes:
  dev-db-data: